##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/programutvecklar/programutvecklare.com
    - npm install --prefix $DEPLOYPATH
    - npm run build --prefix $DEPLOYPATH
    - /usr/local/cpanel/3rdparty/bin/git --work-tree=$DEPLOYPATH --git-dir=$DEPLOYPATH/.git pull origin master